#Category 1: Basic Data Exploration

In [4]:
#1.	Load & Inspect: Load the dataset and display the first 10 rows.
import pandas as pd
df=pd.read_csv("Downloads/online_shopping_customer_behavior (1).csv")
df.head(10)

,customer_id,gender,age,country,device_type,product_category,time_spent_minutes,items_viewed,items_purchased,total_spent_usd
0,CUST_1,Male,40,Australia,Tablet,Clothing,87,12,8,1187
1,CUST_2,Female,38,Pakistan,Tablet,Electronics,71,22,3,153
2,CUST_3,Male,36,UK,Tablet,Clothing,59,20,8,1055
3,CUST_4,Male,36,Pakistan,Mobile,Clothing,39,18,3,991
4,CUST_5,Male,53,Canada,Desktop,Electronics,3,1,1,588
5,CUST_6,Female,46,UK,Desktop,Books,76,30,3,252
6,CUST_7,Male,35,USA,Mobile,Home,7,33,5,1129
7,CUST_8,Male,19,Canada,Desktop,Electronics,49,24,5,706
8,CUST_9,Male,18,UK,Tablet,Sports,26,14,4,100
9,CUST_10,Female,64,Australia,Desktop,Books,33,36,0,1412

In [5]:
#2.	Dataset Info: Display the summary information (data types, non-null counts, and memory usage) of the DataFrame.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1800 entries, 0 to 1799
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         1800 non-null   object
 1   gender              1800 non-null   object
 2   age                 1800 non-null   int64
 3   country             1800 non-null   object
 4   device_type         1800 non-null   object
 5   product_category    1800 non-null   object
 6   time_spent_minutes  1800 non-null   int64
 7   items_viewed        1800 non-null   int64
 8   items_purchased     1800 non-null   int64
 9   total_spent_usd     1800 non-null   int64
dtypes: int64(5), object(5)
memory usage: 140.8+ KB

In [6]:
#3.	Descriptive Statistics: Generate descriptive statistics (mean, min, max, std, etc.) for all numerical columns.
df.describe()

,age,time_spent_minutes,items_viewed,items_purchased,total_spent_usd
count,1800.000000,1800.000000,1800.000000,1800.000000,1800.000000
mean,41.144444,60.544444,24.542778,4.606667,778.503333
std,13.481514,34.717237,14.041840,2.852841,434.788777
min,18.000000,1.000000,1.000000,0.000000,5.000000
25%,30.000000,30.000000,13.000000,2.000000,400.750000
50%,41.000000,60.000000,24.000000,5.000000,802.000000
75%,53.000000,91.000000,36.000000,7.000000,1146.250000
max,64.000000,119.000000,49.000000,9.000000,1499.000000

In [11]:
#4.	Column Names: List all the column names present in the dataset.
df.columns

Index(['customer_id', 'gender', 'age', 'country', 'device_type',
       'product_category', 'time_spent_minutes', 'items_viewed',
       'items_purchased', 'total_spent_usd'],
      dtype='object')

In [14]:
#5.	Unique Values: How many unique countries are represented in the dataset?
df["country"].unique()

array(['Australia', 'Pakistan', 'UK', 'Canada', 'USA', 'India'],
      dtype=object)

In [15]:
df["country"].nunique()

6

In [16]:
#6.	Categories: List all the unique product categories found in the product_category column.
df["product_category"].unique()

array(['Clothing', 'Electronics', 'Books', 'Home', 'Sports', 'Beauty'],
      dtype=object)

In [18]:
#7.	Shape: Find the total number of rows and columns in the DataFrame
df.shape

(1800, 10)

In [21]:
#8.	Null Check: Check if there are any missing values in the entire dataset
df.isnull()

,customer_id,gender,age,country,device_type,product_category,time_spent_minutes,items_viewed,items_purchased,total_spent_usd
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
1795,False,False,False,False,False,False,False,False,False,False
1796,False,False,False,False,False,False,False,False,False,False
1797,False,False,False,False,False,False,False,False,False,False
1798,False,False,False,False,False,False,False,False,False,False
1799,False,False,False,False,False,False,False,False,False,False

In [22]:
df.isnull().sum()

customer_id           0
gender                0
age                   0
country               0
device_type           0
product_category      0
time_spent_minutes    0
items_viewed          0
items_purchased       0
total_spent_usd       0
dtype: int64

In [24]:
#9.	Specific Selection: Display only the customer_id and total_spent_usd columns for the first 5 rows.
df[["customer_id","total_spent_usd"]].head()

  customer_id  total_spent_usd
0      CUST_1             1187
1      CUST_2              153
2      CUST_3             1055
3      CUST_4              991
4      CUST_5              588

In [28]:
#10.Data Types: Convert the age column to a float data type and then back to an integer.
df["age"]=df["age"].astype(float)
df

,customer_id,gender,age,country,device_type,product_category,time_spent_minutes,items_viewed,items_purchased,total_spent_usd
0,CUST_1,Male,40.0,Australia,Tablet,Clothing,87,12,8,1187
1,CUST_2,Female,38.0,Pakistan,Tablet,Electronics,71,22,3,153
2,CUST_3,Male,36.0,UK,Tablet,Clothing,59,20,8,1055
3,CUST_4,Male,36.0,Pakistan,Mobile,Clothing,39,18,3,991
4,CUST_5,Male,53.0,Canada,Desktop,Electronics,3,1,1,588
...,...,...,...,...,...,...,...,...,...,...
1795,CUST_1796,Female,62.0,USA,Mobile,Clothing,61,30,2,425
1796,CUST_1797,Male,20.0,USA,Desktop,Clothing,87,12,3,1344
1797,CUST_1798,Female,44.0,India,Mobile,Electronics,21,35,0,1194
1798,CUST_1799,Male,60.0,Pakistan,Mobile,Clothing,88,11,3,1231
1799,CUST_1800,Male,57.0,Canada,Mobile,Clothing,68,44,0,472

In [31]:
df["age"]=df["age"].astype(int)
df

,customer_id,gender,age,country,device_type,product_category,time_spent_minutes,items_viewed,items_purchased,total_spent_usd
0,CUST_1,Male,40,Australia,Tablet,Clothing,87,12,8,1187
1,CUST_2,Female,38,Pakistan,Tablet,Electronics,71,22,3,153
2,CUST_3,Male,36,UK,Tablet,Clothing,59,20,8,1055
3,CUST_4,Male,36,Pakistan,Mobile,Clothing,39,18,3,991
4,CUST_5,Male,53,Canada,Desktop,Electronics,3,1,1,588
...,...,...,...,...,...,...,...,...,...,...
1795,CUST_1796,Female,62,USA,Mobile,Clothing,61,30,2,425
1796,CUST_1797,Male,20,USA,Desktop,Clothing,87,12,3,1344
1797,CUST_1798,Female,44,India,Mobile,Electronics,21,35,0,1194
1798,CUST_1799,Male,60,Pakistan,Mobile,Clothing,88,11,3,1231
1799,CUST_1800,Male,57,Canada,Mobile,Clothing,68,44,0,472

Category 2: Filtering & Sorting

In [34]:
#1.	Age Filter: Find all customers who are older than 60 years.
df[df['age']>60]

,customer_id,gender,age,country,device_type,product_category,time_spent_minutes,items_viewed,items_purchased,total_spent_usd
9,CUST_10,Female,64,Australia,Desktop,Books,33,36,0,1412
25,CUST_26,Female,61,UK,Tablet,Home,1,49,8,697
28,CUST_29,Female,61,India,Tablet,Beauty,35,43,6,1365
33,CUST_34,Female,63,USA,Tablet,Books,55,42,9,1119
42,CUST_43,Female,62,Canada,Desktop,Books,88,47,5,1334
...,...,...,...,...,...,...,...,...,...,...
1741,CUST_1742,Female,63,Canada,Desktop,Sports,24,1,6,840
1759,CUST_1760,Male,61,India,Tablet,Electronics,15,41,9,1195
1782,CUST_1783,Female,64,Pakistan,Desktop,Electronics,71,2,3,576
1784,CUST_1785,Male,63,Canada,Mobile,Home,94,39,9,1388
1795,CUST_1796,Female,62,USA,Mobile,Clothing,61,30,2,425

In [37]:
#2.	Location & Device: Filter the data for customers from 'USA' who used a 'Mobile' device
#method 1
df[(df['country'] == 'USA') & (df['device_type'] == 'Mobile')]

,customer_id,gender,age,country,device_type,product_category,time_spent_minutes,items_viewed,items_purchased,total_spent_usd
6,CUST_7,Male,35,USA,Mobile,Home,7,33,5,1129
13,CUST_14,Male,59,USA,Mobile,Books,2,31,0,1306
16,CUST_17,Female,40,USA,Mobile,Sports,32,24,9,584
52,CUST_53,Male,62,USA,Mobile,Clothing,52,2,8,1472
56,CUST_57,Female,28,USA,Mobile,Books,80,7,1,1098
...,...,...,...,...,...,...,...,...,...,...
1730,CUST_1731,Female,64,USA,Mobile,Sports,71,44,4,728
1737,CUST_1738,Male,38,USA,Mobile,Books,18,46,4,283
1769,CUST_1770,Male,22,USA,Mobile,Beauty,71,30,3,31
1773,CUST_1774,Female,25,USA,Mobile,Electronics,116,35,3,89
1795,CUST_1796,Female,62,USA,Mobile,Clothing,61,30,2,425

In [45]:
# method 2
df.groupby(['country', 'device_type']).size()

country    device_type
Australia  Desktop        102
           Mobile          97
           Tablet          92
Canada     Desktop        105
           Mobile          86
           Tablet         114
India      Desktop         87
           Mobile          85
           Tablet          91
Pakistan   Desktop        106
           Mobile         103
           Tablet         121
UK         Desktop        104
           Mobile          87
           Tablet         105
USA        Desktop         96
           Mobile         105
           Tablet         114
dtype: int64

In [47]:
df.groupby(['country','device_type']).size().loc('USA','mobile')

TypeError: _LocationIndexer.__call__() takes from 1 to 2 positional arguments but 3 were given

In [49]:
df.groupby(['country','device_type']).size().loc['USA','Mobile']

np.int64(105)